import { v4 as uuid } from "uuid";

// ! This Data Must You Recieve It From BackEnd Dev

// This Data Is Just For Testing

export const data = [
  {
    id: uuid(),
    title: "وجبه افطار",
    description: "وصف وجبة افطار",
    snackImage: "Bfast.jpg",
    price: 5000,
    category: "فطور",
  },
  {
    id: uuid(),
    title: "وجبه غداء",
    description: "وصف وجبة غداء",
    snackImage: "lunch.jpg",
    price: 100000,
    category: "غداء",
  },
  {
    id: uuid(),
    title: "وجبه افطار",
    description: "وصف وجبة افطار",
    snackImage: "Bfast.jpg",
    price: 5000,
    category: "فطور",
  },
  {
    id: uuid(),
    title: "وجبه عشاء",
    description: "وصف وجبة عشاء",
    snackImage: "dinner.jpg",
    price: 20000,
    category: "عشاء",
  },
  {
    id: uuid(),
    title: "وجبه غداء",
    description: "وصف وجبة غداء",
    snackImage: "lunch.jpg",
    price: 100000,
    category: "غداء",
  },
  {
    id: uuid(),
    title: "وجبه غداء",
    description: "وصف وجبة غداء",
    snackImage: "lunch.jpg",
    price: 100000,
    category: "غداء",
  },
  {
    id: uuid(),
    title: "وجبه افطار",
    description: "وصف وجبة افطار",
    snackImage: "Bfast.jpg",
    price: 5000,
    category: "فطور",
  },
  {
    id: uuid(),
    title: "وجبه افطار",
    description: "وصف وجبة افطار",
    snackImage: "Bfast.jpg",
    price: 5000,
    category: "فطور",
  },
  {
    id: uuid(),
    title: "وجبه عشاء",
    description: "وصف وجبة عشاء",
    snackImage: "dinner.jpg",
    price: 20000,
    category: "عشاء",
  },
  {
    id: uuid(),
    title: "وجبه غداء",
    description: "وصف وجبة غداء",
    snackImage: "lunch.jpg",
    price: 100000,
    category: "غداء",
  },
  {
    id: uuid(),
    title: "وجبه افطار",
    description: "وصف وجبة افطار",
    snackImage: "Bfast.jpg",
    price: 5000,
    category: "فطور",
  },
  {
    id: uuid(),
    title: "وجبه غداء",
    description: "وصف وجبة غداء",
    snackImage: "lunch.jpg",
    price: 100000,
    category: "غداء",
  },
  {
    id: uuid(),
    title: "وجبه افطار",
    description: "وصف وجبة افطار",
    snackImage: "Bfast.jpg",
    price: 5000,
    category: "فطور",
  },
  {
    id: uuid(),
    title: "وجبه عشاء كبيرة",
    description: "وصف وجبة عشاء",
    snackImage: "dinner.jpg",
    price: 25000,
    category: "عشاء",
  },
  {
    id: uuid(),
    title: "وجبه افطار",
    description: "وصف وجبة افطار",
    snackImage: "Bfast.jpg",
    price: 5000,
    category: "فطور",
  },
  {
    id: uuid(),
    title: "وجبه افطار",
    description: "وصف وجبة افطار",
    snackImage: "Bfast.jpg",
    price: 5000,
    category: "فطور",
  },
  {
    id: uuid(),
    title: "وجبه عشاء",
    description: "وصف وجبة عشاء",
    snackImage: "dinner.jpg",
    price: 20000,
    category: "عشاء",
  },
];
